### ISSUE TITLE
Garantir Requisitos

### ISSUE THREAD

**Issue by TheMarini** [mira-ej/hotsite-arte-sacra#9]
** --- FUNCIONAIS --- **
- [ ] [RF01] Os dados captados dos clientes deverão ser exportados em CSV (Excel)
- [ ] [RF02] Após a submissão do formulário, cada cliente deve receber um e-mail de confirmação do preenchimento.
- [ ] [RF03] Os campos {?} são de preenchimento obrigatório

** --- NÃO FUNCIONAIS --- **
- [ ] [RNF01] O site deverá conter uma máscara de preenchimento para o telefone com ddd e número.
- [ ] [RNF02] As cores devem estar de acordo com a identidade visual da marca
- [ ] [RNF03] O site deverá, de alguma forma, deixar claro que o preenchimento do formulário não garante a participação do sorteio. A participação do sorteio está condicionada ao preenchimento da pesquisa que será enviada pela Opinion Box.
- [ ] [RNF04] O hotsite deverá ficar no ar em torno de 3 semanas

**Comment by TheMarini** [comment]
**Questionamentos:**
- [RF01] -> Quem realizará essa exportação?
- [RNF04] -> Este período está confirmado e validado?

**TODO:**
- [ ] Perguntar sobre como a exportação será realizada e, se for feita por nós, perguntar se o servidor utiliza PHPMyAdmin
- [ ] Validar o período/meta que o hotsite irá ficar no ar
- [ ] Perguntar o que deverá ser feito depois deste período/meta ser atingida
